{% set name = "jupyterhub-idle-culler" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3eaaa924a7e410f9a06188f82629846631b7aefc2dad9047de19326bfab76bf4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - cull_idle_servers.py = jupyterhub_idle_culler:main
    - jupyterhub-idle-culler = jupyterhub_idle_culler:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - tornado
    - python-dateutil

test:
  imports:
    - jupyterhub_idle_culler
  commands:
    - cull_idle_servers.py --help
    - jupyterhub-idle-culler --help

about:
  home: https://github.com/jupyterhub/jupyterhub-idle-culler
  license: BSD-3-Clause
  license_family: BSD
  # Opened license packaging PR upstream: https://github.com/jupyterhub/jupyterhub-idle-culler/pull/3
  license_file: COPYING.md
  summary: JupyterHub service to cull idle servers and users
  description: |
    jupyterhub-idle-culler provides a JupyterHub service to cull and shut down
    idle notebook servers and users on a JupyterHub deployment.
  doc_url: https://github.com/jupyterhub/jupyterhub-idle-culler/blob/master/README.rst
  dev_url: https://github.com/jupyterhub/jupyterhub-idle-culler

extra:
  recipe-maintainers:
